version: "3.3"
services:

  productiontracker-client:
    build: ../productiontracker-client
    container_name: productiontracker-client
    volumes:
      - ../productiontracker-client/src:/app/src
    restart: always
    ports:
      - '4200:4200'
    expose:
      - '4200'
    depends_on:
      - probono-rest

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    volumes:
      - ./database:/data/db
    ports:
      - '27017:27017'

  mongodb-seed:
    build: ./mongodb-seed
    container_name: mongodb-seed
    depends_on:
      - mongodb

  probono-rest:
    image: 308code/probono-rest:1.0-SNAPSHOT
    container_name: probono-rest
    environment:
      RUN_ENV: 'development' # 'test' 'production'
      MONGO_PROBONO_USER_NAME: 'probono'
      MONGO_PROBONO_PSWD: 'probono_1'
      MONGO_PROBONO_DB_NAME: 'probono'
    restart: always
    depends_on:
      - mongodb
    ports:
      - '8080:8080'
    expose:
      - '8080'

    healthcheck:
      test: [ "CMD", "curl", "-f", "localhost:8080/api/healthcheck" ]
      interval: "15s"
      timeout: "5s"
      retries: 20
